#!/usr/bin/env python3
# Resolves proxy/requirements.in and writes a hash-pinned requirements.txt.
# Uses only pip and Python stdlib - no third-party tools required.
#
# Platform note: pip resolves platform-specific wheels, so this script must
# run on the same OS/arch as the container target (Linux x86_64).
# On a non-Linux host, run via the container base image instead:
#   podman run --rm -v "$(pwd):/work" -w /work python:3.12-slim python3 lock.py
import json
import subprocess
import sys
import tempfile
import venv
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent

print("Creating temporary venv for dependency resolution...")
with tempfile.TemporaryDirectory() as tmpdir:
    venv.create(tmpdir, with_pip=True)
    pip = Path(tmpdir) / "bin" / "pip"
    report_path = Path(tmpdir) / "report.json"

    print("Resolving dependencies from requirements.in...")
    subprocess.run(
        [pip, "install", "--quiet", "--dry-run",
         "--report", report_path,
         "-r", SCRIPT_DIR / "requirements.in"],
        check=True,
    )

    with open(report_path) as f:
        report = json.load(f)

print("Generating requirements.txt with pinned versions and hashes...")
lines = []
for pkg in report["install"]:
    name = pkg["metadata"]["name"]
    version = pkg["metadata"]["version"]
    hashes = pkg["download_info"]["archive_info"]["hashes"]
    hash_args = " \\\n".join(
        f"    --hash={algo}:{digest}" for algo, digest in sorted(hashes.items())
    )
    lines.append(f"{name}=={version} \\\n{hash_args}")

lines.sort(key=str.lower)

out_path = SCRIPT_DIR / "requirements.txt"
with open(out_path, "w") as f:
    f.write("# Generated by lock.py - do not edit manually.\n")
    f.write("# To update: edit requirements.in and re-run lock.py.\n\n")
    f.write("\n".join(lines) + "\n")

print(f"Wrote {len(lines)} packages to {out_path}")
