#!/bin/bash
set -euo pipefail

# Check whether the Vertex metadata server should start
_vertex_enabled() {
    python3 - <<'EOF'
import sys, yaml
try:
    with open("/config/proxy.yaml") as f:
        cfg = yaml.safe_load(f)
    providers = cfg.get("providers", [])
    v = next((p for p in providers if p.get("name") == "vertex"), {})
    sys.exit(0 if v.get("enabled") and v.get("metadata_server") else 1)
except Exception:
    sys.exit(1)
EOF
}

# --- Start GCE metadata server (Vertex only) ---------------------------------
if _vertex_enabled; then
    echo "[proxy] Starting GCE metadata server on :9090..."
    python3 /app/metadata_server.py &
    META_PID=$!
fi

# --- Start mitmweb -----------------------------------------------------------
echo "[proxy] Starting mitmweb on :8080 (proxy) / :8081 (UI)..."
mitmweb \
    --listen-host 0.0.0.0 --listen-port 8080 \
    --web-host    0.0.0.0 --web-port    8081 \
    --scripts /addons/injector.py \
    --scripts /addons/logger.py \
    --set block_global=false \
    --no-web-open-browser &
MITM_PID=$!

# --- Wait for CA cert (generated by mitmproxy on first start) ----------------
CA="$HOME/.mitmproxy/mitmproxy-ca-cert.pem"
printf "[proxy] Waiting for CA cert"
until [ -f "$CA" ]; do
    printf "."
    sleep 1
done
echo " ready."

# --- Clean shutdown on SIGTERM/SIGINT ----------------------------------------
trap 'kill "${MITM_PID}" "${META_PID:-}" 2>/dev/null; exit 0' TERM INT

wait -n "${MITM_PID}" "${META_PID:-}"
EXIT_CODE=$?
echo "[proxy] A service exited (code $EXIT_CODE); shutting down."
kill "${MITM_PID}" "${META_PID:-}" 2>/dev/null
exit "$EXIT_CODE"
