FROM fedora:44

RUN dnf install -y \
        curl \
        git \
        ca-certificates \
        proxychains-ng \
        vim \
        tmux \
        jq \
        ripgrep \
    && dnf clean all

COPY start.sh /start.sh

WORKDIR /workspace
ENTRYPOINT ["/start.sh"]
