FROM fedora:44

RUN dnf install -y \
        curl \
        git \
        ca-certificates \
        proxychains-ng \
        vim \
        tmux \
        jq \
    && dnf clean all

RUN git config --global user.email "agent@agentbox" && \
    git config --global user.name "Agent"

COPY start.sh /start.sh

WORKDIR /workspace
ENTRYPOINT ["/start.sh"]
