#!/bin/bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Trust the mitmproxy CA cert (generated by proxy container on first start,
# shared via the proxy-ca named volume mounted at /proxy-ca).
# ---------------------------------------------------------------------------
CA=/proxy-ca/mitmproxy-ca-cert.pem
printf "[agent] Waiting for proxy CA cert"
until [ -f "$CA" ]; do
    printf "."
    sleep 1
done
echo " found."

# System trust store (curl, wget, apt, etc.)
cp "$CA" /usr/local/share/ca-certificates/proxy-ca.crt
update-ca-certificates --fresh >/dev/null 2>&1

# Node.js respects this env var for apps that bypass the system store
export NODE_EXTRA_CA_CERTS="$CA"
# Python requests / httpx
export REQUESTS_CA_BUNDLE="$CA"

# ---------------------------------------------------------------------------
# Git workspace setup
# Clone from the read-only source bundle, add the output bare repo as remote.
# The host's .git directory is NEVER mounted; the agent gets a fresh repo.
# ---------------------------------------------------------------------------
if [ -f /source/project.bundle ] && [ ! -d /workspace/.git ]; then
    echo "[agent] Cloning from source bundle..."
    git clone /source/project.bundle /workspace
    git -C /workspace remote rename origin source     # mark as read-only origin
    git -C /workspace remote add output /output/repo.git
    echo "[agent] Workspace ready. Push work with: git push output HEAD:agent-work"
    echo ""
fi

# ---------------------------------------------------------------------------
# Shell mode: run setup but drop to bash instead of the harness
# (used by: sandbox shell)
# ---------------------------------------------------------------------------
if [ "${1:-}" = "--shell" ]; then
    echo "[agent] Dropping to shell. The proxy is active; all traffic is monitored."
    exec /bin/bash
fi

# ---------------------------------------------------------------------------
# Start the configured harness via proxychains (transparent proxy routing)
# ---------------------------------------------------------------------------
HARNESS="${AGENT_HARNESS:-claude}"
echo "[agent] Starting ${HARNESS}..."
exec proxychains4 -q "${HARNESS}" "$@"
